# Generated by Django 5.2.7 on 2025-10-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=10)),
                ('ingresos_mantenimiento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dppp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingresos_netos_mantenimiento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingresos_cuota_extraordinaria', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cuota_ordinaria_retroactiva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('revision_csau', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('depositos_garantia_obra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingresos_intereses_cuotas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingresos_rendimiento_inversiones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sanciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recuperacion_seguro_danios', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recuperacion_gastos_cobranza', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('depositos_no_identificados', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingresos_reales_vs_fact', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('diferencia_ingresos_fac_vs_cobrados', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
