# Generated by Django 5.2 on 2025-10-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_movimientolog_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientolog',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
